name: football_coach
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=hd77b12b_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - console_shortcut=0.1.1=haa95532_6
  - cpython=3.9.23=py39hd8ed1ab_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py39h1f3cc84_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=hac47afa_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h827c3e9_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39hb328d1f_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pytesseract=0.3.13=pyhd8ed1ab_1
  - python=3.9.23=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=8_cp39
  - pywin32=311=py39h5fb4b08_0
  - pyzmq=27.0.2=py39h248659b_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.4=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py39h0802e32_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h56299aa_0
  - pip:
      - blinker==1.9.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - filetype==1.2.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - idna==3.7
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lap==0.5.12
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - ml-dtypes==0.5.3
      - moviepy==2.2.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - onnx==1.19.0
      - onnxruntime==1.19.2
      - opencv-python==4.11.0.86
      - pi-heif==1.1.1
      - pillow-avif-plugin==1.5.2
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - proglog==0.1.12
      - protobuf==6.32.1
      - pybboxes==0.1.6
      - pycocotools==2.0.10
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - roboflow==1.2.9
      - safetensors==0.6.2
      - sahi==0.11.36
      - scipy==1.13.1
      - segment-anything==1.0
      - shapely==2.0.7
      - sympy==1.13.1
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - torch-vision==0.1.6.dev0
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.15.0
      - ultralytics==8.3.204
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - yt-dlp==2025.10.14
prefix: C:\Users\traep\Anaconda3\envs\football_coach
